project 'smilechat.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'smilechat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for smilechat
pod 'Alamofire'
pod 'Firebase/Database'
pod 'Firebase/Core'
pod 'Socket.IO-Client-Swift'
pod 'SwiftyJSON'
pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
end
